name: Nightly Release
on:
  push:
  workflow_dispatch: {}
jobs:
  build-release:
    name: Build and release Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token for authentication
      - name: Build Docker image
        run: |
          docker build \
          -t "ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA:0:7}" \
          -t "ghcr.io/${GITHUB_REPOSITORY}:nightly" .
      - name: Release Docker image
        run: |
          docker push "ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA:0:7}"
          docker push "ghcr.io/${GITHUB_REPOSITORY}:nightly"
